# Build initial image
ARG IMAGE_NODE_ALPINE_VERSION=node:14-alpine3.15 

FROM ${IMAGE_NODE_ALPINE_VERSION} as builder

LABEL maintainer="Renato Gomes <renatogomessilverio@gmail.com>"

RUN /bin/sh -c "apk add --no-cache bash" && \
    apk update && apk add curl wget git vim htop python3 openssh py3-pip busybox-extras figlet build-base && \
    npm install -g @angular/cli@10.2.3

SHELL ["/bin/bash", "-c"]

WORKDIR /APP

# Build final image
FROM ${IMAGE_NODE_ALPINE_VERSION} as runner

LABEL maintainer="Renato Gomes <renatogomessilverio@gmail.com>"

COPY --from=builder /usr/lib /usr/lib
COPY --from=builder /usr/local/share /usr/local/share
COPY --from=builder /usr/local/lib /usr/local/lib
COPY --from=builder /usr/local/include /usr/local/include
COPY --from=builder /usr/local/bin /usr/local/bin

RUN apk add git && /bin/sh -c "apk add --no-cache bash" && mkdir -p /APP && echo 'figlet -t "Lapig Docker NTVI"' >> ~/.bashrc

SHELL ["/bin/bash", "-c"]

WORKDIR /APP
